name: umi
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip=22.1
  - click
  - numpy=1.24
  - scipy=1.11
  - numba=0.57
  - pandas=2.1
  - py-opencv=4.7
  - ipykernel=6.23
  - matplotlib=3.7
  - av=10.0
  - k3d=2.15
  - pyyaml=6.0
  - tqdm=4.65
  - zarr=2.16
  - numcodecs=0.11
  - dill=0.3.7
  - einops=0.6.1
  - scikit-video=1.1
  - python-lmdb=1.4
  - cython=0.29
  - boto3=1.33
  - exiftool=12
  - aiohttp=3.9
  - aiofiles=23.2
  - pip:
    - imagecodecs==2023.9.18
    - PyExifTool==0.5
